"""initial schema - foundations, origination, underwriting

Revision ID: 90101a722b85
Revises: 
Create Date: 2026-08-28 03:05:02.013274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90101a722b85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lending_institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered_business_name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('kra_pin', sa.String(length=50), nullable=False),
    sa.Column('operating_license_type', sa.String(length=100), nullable=True),
    sa.Column('cbk_license_number', sa.String(length=100), nullable=True),
    sa.Column('head_office_address', sa.String(length=255), nullable=False),
    sa.Column('head_office_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('head_office_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('county_business_permit_number', sa.String(length=255), nullable=True),
    sa.Column('odpc_registration_number', sa.String(length=100), nullable=True),
    sa.Column('estimated_staff_count', sa.Integer(), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_account_number', sa.String(length=100), nullable=True),
    sa.Column('collection_paybill_number', sa.String(length=20), nullable=True),
    sa.Column('default_interest_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('default_penalty_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending_review', 'active', 'suspended')", name='ck_institutions_status_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cbk_license_number'),
    sa.UniqueConstraint('kra_pin'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('market_stalls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_name', sa.String(length=150), nullable=False),
    sa.Column('stall_number', sa.String(length=50), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institution_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lending_institution_id', sa.Integer(), nullable=False),
    sa.Column('market_name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['lending_institution_id'], ['lending_institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institution_markets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institution_markets_lending_institution_id'), ['lending_institution_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lending_institution_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('national_id_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('loan_officer', 'manager', 'admin', 'super_admin')", name='ck_users_role_valid'),
    sa.CheckConstraint("status IN ('pending', 'active', 'suspended')", name='ck_users_status_valid'),
    sa.ForeignKeyConstraint(['lending_institution_id'], ['lending_institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id_number'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_lending_institution_id'), ['lending_institution_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lending_institution_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['lending_institution_id'], ['lending_institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_lending_institution_id'), ['lending_institution_id'], unique=False)

    op.create_table('customer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('national_id_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('monthly_income_range', sa.String(length=50), nullable=True),
    sa.Column('residential_address', sa.String(length=255), nullable=True),
    sa.Column('next_of_kin_name', sa.String(length=150), nullable=True),
    sa.Column('next_of_kin_phone', sa.String(length=20), nullable=True),
    sa.Column('market_stall_id', sa.Integer(), nullable=True),
    sa.Column('credit_tier', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("credit_tier is NULL OR credit_tier IN ('A', 'B', 'C')", name='ck_customer_credit_tier_valid'),
    sa.ForeignKeyConstraint(['market_stall_id'], ['market_stalls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id_number')
    )
    with op.batch_alter_table('customer_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_profiles_market_stall_id'), ['market_stall_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('institution_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lending_institution_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lending_institution_id'], ['lending_institutions.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institution_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institution_documents_lending_institution_id'), ['lending_institution_id'], unique=False)

    op.create_table('credit_score_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_profile_id', sa.Integer(), nullable=False),
    sa.Column('previous_tier', sa.String(length=10), nullable=True),
    sa.Column('new_tier', sa.String(length=10), nullable=False),
    sa.Column('score_components', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_score_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_score_log_customer_profile_id'), ['customer_profile_id'], unique=False)

    op.create_table('customer_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_profile_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_profile_id', 'badge_id', name='uq_customer_badge_once')
    )
    with op.batch_alter_table('customer_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_badges_badge_id'), ['badge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_badges_customer_profile_id'), ['customer_profile_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_profile_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_customer_profile_id'), ['customer_profile_id'], unique=False)

    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lending_institution_id', sa.Integer(), nullable=False),
    sa.Column('customer_profile_id', sa.Integer(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('term_days', sa.Integer(), nullable=False),
    sa.Column('repayment_frequency', sa.String(length=20), nullable=False),
    sa.Column('loan_purpose', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('disbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("repayment_frequency IN ('daily', 'weekly', 'lump_sum')", name='ck_loans_repayment_frequency_valid'),
    sa.CheckConstraint("status IN ('pending', 'active', 'restructured', 'fully_paid', 'defaulted')", name='ck_loans_status_valid'),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['lending_institution_id'], ['lending_institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_customer_profile_id'), ['customer_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_lending_institution_id'), ['lending_institution_id'], unique=False)

    op.create_table('loyalty_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_profile_id', sa.Integer(), nullable=False),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loyalty_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_points_customer_profile_id'), ['customer_profile_id'], unique=True)

    op.create_table('savings_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_profile_id', sa.Integer(), nullable=False),
    sa.Column('total_savings_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('days_saved_count', sa.Integer(), nullable=False),
    sa.Column('savings_start_date', sa.Date(), nullable=True),
    sa.Column('is_savings_mature', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('savings_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savings_accounts_customer_profile_id'), ['customer_profile_id'], unique=True)

    op.create_table('loan_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('maker_id', sa.Integer(), nullable=False),
    sa.Column('checker_id', sa.Integer(), nullable=True),
    sa.Column('maker_notes', sa.Text(), nullable=True),
    sa.Column('checker_notes', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('maker_action_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checker_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("decision IN ('pending', 'approved', 'rejected')", name='ck_loan_approvals_decision_valid'),
    sa.ForeignKeyConstraint(['checker_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['maker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_approvals_loan_id'), ['loan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_approvals_loan_id'))

    op.drop_table('loan_approvals')
    with op.batch_alter_table('savings_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_accounts_customer_profile_id'))

    op.drop_table('savings_accounts')
    with op.batch_alter_table('loyalty_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_points_customer_profile_id'))

    op.drop_table('loyalty_points')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_lending_institution_id'))
        batch_op.drop_index(batch_op.f('ix_loans_customer_profile_id'))

    op.drop_table('loans')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_customer_profile_id'))

    op.drop_table('documents')
    with op.batch_alter_table('customer_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_badges_customer_profile_id'))
        batch_op.drop_index(batch_op.f('ix_customer_badges_badge_id'))

    op.drop_table('customer_badges')
    with op.batch_alter_table('credit_score_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_score_log_customer_profile_id'))

    op.drop_table('credit_score_log')
    with op.batch_alter_table('institution_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institution_documents_lending_institution_id'))

    op.drop_table('institution_documents')
    with op.batch_alter_table('customer_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_customer_profiles_market_stall_id'))

    op.drop_table('customer_profiles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_lending_institution_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_lending_institution_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('institution_markets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institution_markets_lending_institution_id'))

    op.drop_table('institution_markets')
    op.drop_table('market_stalls')
    op.drop_table('lending_institutions')
    op.drop_table('badges')
    # ### end Alembic commands ###
